spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Shop?createDatabaseIfNotExist=true&esessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: Root

  jpa: 
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
